# Generated by Django 5.0 on 2026-02-14 09:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Field Officer', 'Field Officer'), ('District Admin', 'District Admin'), ('State Admin', 'State Admin')], default='Field Officer', max_length=50)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WaterSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('village', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('date_collected', models.DateField(default=django.utils.timezone.now)),
                ('turbidity', models.FloatField(help_text='Turbidity in NTU')),
                ('ph', models.FloatField(help_text='pH value')),
                ('ecoli_present', models.BooleanField(default=False, help_text='Presence of E.coli')),
                ('nitrate_level', models.FloatField(help_text='Nitrate level in mg/L')),
                ('water_source', models.CharField(choices=[('Borewell', 'Borewell'), ('River', 'River'), ('Lake', 'Lake'), ('Panchayat Supply', 'Panchayat Supply'), ('Other', 'Other')], max_length=100)),
                ('contamination_index', models.FloatField(blank=True, null=True)),
                ('risk_score', models.FloatField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('village', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('risk_score', models.FloatField()),
                ('alert_level', models.CharField(choices=[('Green', 'Low Risk'), ('Yellow', 'Moderate Risk'), ('Red', 'High Risk')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('resolution_notes', models.TextField(blank=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL)),
                ('sample', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='monitoring.watersample')),
            ],
        ),
    ]
