# Generated by Django 5.0 on 2026-03-16 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_watersample_cause_watersample_effect_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watersample',
            name='water_source',
            field=models.CharField(choices=[('Borewell', 'Borewell'), ('River', 'River'), ('Lake', 'Lake'), ('Panchayat Supply', 'Panchayat Supply'), ('Tapwater', 'Tapwater'), ('Other', 'Other')], max_length=100),
        ),
    ]
