# Generated by Django 5.0 on 2026-03-16 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_alter_watersample_water_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='watersample',
            name='ammonia',
            field=models.FloatField(default=0.0, help_text='Ammonia in mg/L'),
        ),
        migrations.AddField(
            model_name='watersample',
            name='arsenic',
            field=models.FloatField(default=0.0, help_text='Arsenic in mg/L'),
        ),
        migrations.AddField(
            model_name='watersample',
            name='bod',
            field=models.FloatField(default=0.0, help_text='BOD in mg/L'),
        ),
        migrations.AddField(
            model_name='watersample',
            name='cadmium',
            field=models.FloatField(default=0.0, help_text='Cadmium in mg/L'),
        ),
        migrations.AddField(
            model_name='watersample',
            name='chloride',
            field=models.FloatField(default=0.0, help_text='Chloride in mg/L'),
        ),
        migrations.AddField(
            model_name='watersample',
            name='cod',
            field=models.FloatField(default=0.0, help_text='COD in mg/L'),
        ),
        migrations.AddField(
            model_name='watersample',
            name='dissolved_oxygen',
            field=models.FloatField(default=0.0, help_text='DO in mg/L'),
        ),
        migrations.AddField(
            model_name='watersample',
            name='fluoride',
            field=models.FloatField(default=0.0, help_text='Fluoride in mg/L'),
        ),
        migrations.AddField(
            model_name='watersample',
            name='iron',
            field=models.FloatField(default=0.0, help_text='Iron in mg/L'),
        ),
        migrations.AddField(
            model_name='watersample',
            name='lead',
            field=models.FloatField(default=0.0, help_text='Lead in mg/L'),
        ),
        migrations.AddField(
            model_name='watersample',
            name='mercury',
            field=models.FloatField(default=0.0, help_text='Mercury in mg/L'),
        ),
        migrations.AddField(
            model_name='watersample',
            name='nitrite_level',
            field=models.FloatField(default=0.0, help_text='Nitrite level in mg/L'),
        ),
        migrations.AddField(
            model_name='watersample',
            name='sulphate',
            field=models.FloatField(default=0.0, help_text='Sulphate in mg/L'),
        ),
    ]
