# Generated by Django 5.0 on 2026-03-16 19:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0005_watersample_ammonia_watersample_arsenic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VillageProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Village Name', max_length=100, unique=True)),
                ('district', models.CharField(max_length=100)),
                ('population', models.IntegerField(default=5000, help_text='Estimated Population')),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='PHCHealthReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reported', models.DateField(default=django.utils.timezone.now)),
                ('gastro_cases', models.IntegerField(default=0, help_text='Sudden spike in diarrhea/vomiting')),
                ('fever_cases', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, help_text='Officer notes on outbreak severity')),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_reports', to='monitoring.villageprofile')),
            ],
        ),
    ]
