# Generated by Django 5.0 on 2026-03-17 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0006_villageprofile_phchealthreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='dispatched',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alert',
            name='dispatched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='dispatched_team_notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alert',
            name='public_notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alert',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
