# Generated by Django 5.0 on 2026-03-10 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_alter_watersample_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='watersample',
            name='cause',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watersample',
            name='effect',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watersample',
            name='phone_number',
            field=models.CharField(blank=True, help_text='WhatsApp Number for Alerts', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='watersample',
            name='remedy',
            field=models.TextField(blank=True, null=True),
        ),
    ]
